# Default values for aws-secrets-manager-secret.
# This is a YAML-formatted file.

nameSuffix: "4593810"

region: us-east-1

secret:
  key: key
  name: cert-manager-secert
  namespace: default

# this chart is expected to be used with the crossplane provider for AWS Secrets Manager
# https://marketplace.upbound.io/providers/upbound/provider-aws-secretsmanager/v1.20.1
# and consumed via an ArgoCD Application of type helm, created via crossplane provider-kubernetes Object
# https://github.com/crossplane-contrib/provider-kubernetes/blob/main/examples/object/object-watching.yaml
