---
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: {{ include "aws-secrets-manager-secret.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"{{/* have SecretVersion pruned prior to Secret */}}
spec:
  forProvider:
    region: {{ .Values.region }}
    secretId: {{ include "aws-secrets-manager-secret.fullname" . }}
    secretIdRef:
      name: {{ include "aws-secrets-manager-secret.fullname" . }}
    secretStringSecretRef:
      key: {{ .Values.secret.key }}
      name: {{ .Values.secret.name }}
      namespace: {{ .Values.secret.namespace }}
---
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  name: {{ include "aws-secrets-manager-secret.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"{{/* have Secret deployed prior to Secret */}}
spec:
  deletionPolicy: Orphan
  forProvider:
    region: {{ .Values.region }}
    forceOverwriteReplicaSecret: false
    recoveryWindowInDays: 0
    name: {{ include "aws-secrets-manager-secret.fullname" . }}
