---
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: {{ include "aws-secrets-manager-secret.fullname" . }}
spec:
  forProvider:
    region: {{ .Values.region }}
    secretId: {{ include "aws-secrets-manager-secret.fullname" . }}
    secretIdRef:
      name: {{ include "aws-secrets-manager-secret.fullname" . }}
    secretStringSecretRef:
      key: {{ .Values.secret.key }}
      name: {{ .Values.secret.name }}
      namespace: {{ .Values.secret.namespace }}
---
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  name: {{ include "aws-secrets-manager-secret.fullname" . }}
spec:
  forProvider:
    deletionPolicy: Orphan
    region: {{ .Values.region }}
    forceOverwriteReplicaSecret: false
    recoveryWindowInDays: 0
    name: {{ include "aws-secrets-manager-secret.fullname" . }}    