name: demo action

on:
  push:
    branches:
      - master

concurrency:
  group: master-only
  cancel-in-progress: false

jobs:
  get_pr_info:
    uses: ./.github/workflows/get-current-pr.yml
    secrets: inherit
    with:
      ref: ${{ github.event.head }} # will be null for PR merge to master events
